### ISSUE TITLE
downloading cli on mac trouble

### ISSUE THREAD

**Issue by maskedband1t** [strongback/strongback-cli#11]
curl -o https://github.com/strongback/strongback-cli/releases/download/v1.2.2/strongback-cli-1.2.2-macos.tar.gz | tar xvz

That ^ does not work for macOX on terminal for some reason. I get a "no Url specified!"

**Comment by MaskedBandit1** [comment]
never mind I just did curl -Lsf and it worked instead of curl -o

**Comment by maskedband1t** [comment]
It still does not work the way I want it to, how can I get it to work when curl -o is not working?
