### ISSUE TITLE
mac OSX downloading problem

### ISSUE THREAD

**Issue by maskedband1t** [strongback/strongback-cli#12]
This issue was closed by you earlier, but my question has not been answered :)

curl -o https://github.com/strongback/strongback-cli/releases/download/v1.2.2/strongback-cli-1.2.2-macos.tar.gz | tar xvz

That ^ does not work for macOX on terminal for some reason. I get a "no Url specified!"

How do I get it to work?

**Comment by rhauch** [comment]
I've corrected the [book](https://strongback.gitbooks.io/using-strongback/content/getting_started.html), which had a typo that did not instruct `curl` to follow redirects via its `-L` flag. Anyway, the correct command for Linux and MacOS is:

    curl -L https://github.com/strongback/strongback-cli/releases/download/v1.2.2/strongback-cli-1.2.2-macos.tar.gz | tar -xvz

Sorry for the inconvenience. BTW, the `-` on the `tar` flags is optional, but it's more conventional to use it so I changed that in the book as well.
