### ISSUE TITLE
Linux CLI - Install command fails if expected folders do not exist

### ISSUE THREAD

**Issue by WawerOS** [strongback/strongback-cli#13]
The exact same problem as issue #11, here is the output with verbose. [log](https://gist.github.com/WawerOS/1f8a72bc6bed2fd6c234754c4d407461)

**Comment by rhauch** [comment]
What version of the CLI was this with?

**Comment by WawerOS** [comment]
version 1.01

**Comment by rhauch** [comment]
@WawerOS, can you please re-try with 1.2.2? See the [list of releases](https://github.com/strongback/strongback-cli/releases). Remember, the strongback CLI still needs to be manually installed/upgraded, and hopefully it will solidify relatively soon so that upgrades are needed far less often.

**Comment by rhauch** [comment]
For #11 I updated the [online book](https://strongback.gitbooks.io/using-strongback/content/getting_started.html) but neglected to update the [README.md](../blob/master/README.md) file. I'll do that now.

**Comment by rhauch** [comment]
The [README.md](../blob/master/README.md) file now has the correct instructions. Sorry about that.
