### ISSUE TITLE
Overwrite not working when project directory exists

### ISSUE THREAD

**Issue by primetoxinz** [strongback/strongback-cli#9]
Attempting to use the command `strongback new-project --overwrite FRCSteamWorks2017` always returns with the error `directory already exists and --overwrite not provided`

Also there is a typo on [this line](https://github.com/strongback/strongback-cli/blob/a55a96d85e981ca13564d17ed241c1f127848c70/main.go#L795) with `overrite` instead of `overwrite`

**Comment by rhauch** [comment]
Thanks for logging this. I hope to address this today.

**Comment by rhauch** [comment]
Release 1.2.1 is now available. Thanks for reporting this!
